name: mega_pro
description: MEGA Pro Downloader
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  dio: ^5.4.0

flutter:
  uses-material-design: true